/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: fc0f544374c76c99d4d539808bb96fee)
interface __BaseEnv_Env {
  DOCUMENTS: R2Bucket
  DB: D1Database
  OCR_QUEUE: Queue
  ASSETS: Fetcher
  GEMINI_MODEL: "gemini-3.5-flash-lite"
  BETTER_AUTH_SECRET: string
  GOOGLE_CLIENT_ID: string
  GOOGLE_CLIENT_SECRET: string
  CREDENTIAL_ENCRYPTION_KEY: string
  MISTRAL_API_KEY: string
  GEMINI_API_KEY: string
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/worker/index")
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string
}
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | "GEMINI_MODEL"
        | "BETTER_AUTH_SECRET"
        | "GOOGLE_CLIENT_ID"
        | "GOOGLE_CLIENT_SECRET"
        | "CREDENTIAL_ENCRYPTION_KEY"
        | "MISTRAL_API_KEY"
        | "GEMINI_API_KEY"
      >
    > {}
}
