from pathlib import Path
from types import TracebackType
from typing import Self

from PIL.Image import Image

class PdfBitmap:
    def close(self) -> None: ...
    def to_pil(self) -> Image: ...

class PdfPage:
    def close(self) -> None: ...
    def render(self, scale: int = 1) -> PdfBitmap: ...

class PdfDocument:
    def __init__(self, input: str | Path) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, traceback: TracebackType | None) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> PdfPage: ...
